run three times

diff --git a/trunk/runScenarios b/trunk/runScenarios
--- a/trunk/runScenarios
+++ b/trunk/runScenarios
@@ -1,14 +1,21 @@
 #!/bin/bash
-echo `date "+%d/%m/%y %H:%M:%S"`" runScenarios"
-echo `date "+%d/%m/%y %H:%M:%S"`" runScenarios" >> log
-
-for i in $(ls $1*map.scen*);
-do
-		echo "$i"
-	   ./bin/hog -scenario $i -nogui $2 >> log
-	   if [ "$?" -ne "0"  ]
-	   then
-		   echo "hog exited with error code $?. terminating";
-		   echo "hog exited with error code $?. terminating" >> log
-	   fi
+stamp=`date "+%d/%m/%y %H:%M:%S"`" $1"
+echo "$stamp runScenarios"
+echo "$stamp runScenarios" >> log
+runs=3;
+for ((x=1;x<=$runs;x++)) ; do
+	for i in $(ls $1*.map.scen*);
+	do
+			echo "$i"
+			./bin/hog -scenario $i -nogui $2 >> log
+			if [ "$?" -ne "0" ]
+			then
+				err="Failed while executing: ./bin/hog -scenario $i -nogui $2";
+				echo $err >> log
+				echo $err
+				exit 1
+			fi
+	done
+	mv results_FlexibleAStar results_FlexibleAStarJump.$x
+#	mv results_HPAStar2 results_HPAStar2RSR.$x
 done
